CREATE TABLE tenants (
user_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
email TEXT NOT NULL );
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE rooms(
room_id CHAR(1) PRIMARY KEY NOT NULL,
rentable INT NOT NULL , price INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS "rent" (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
room_id CHAR(1) NOT NULL,
date TEXT NOT NULL,
paid INTEGER NOT NULL,
receipt_issued INTEGER NOT NULL DEFAULT 0, receipt_sent INTEGER NOT NULL DEFAULT 0);
